// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lazbtfiroxjzgbycvfmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhemJ0Zmlyb3hqemdieWN2Zm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjQ1MzUsImV4cCI6MjA1NjA0MDUzNX0.4AvE_QXJ1tO33E86HARUvifTOKljUdqxB6XwHLqNCEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);